debug: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
